services:
  - type: web
    name: mcp-registry
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: MCP_REGISTRY_DATABASE_URL
        fromDatabase:
          name: mcp-registry-db
          property: connectionString
      - key: MCP_REGISTRY_ENVIRONMENT
        value: production
      - key: MCP_REGISTRY_SEED_FROM
        value: /app/data/seed.json
      - key: MCP_REGISTRY_ENABLE_REGISTRY_VALIDATION
        value: "false"
      - key: MCP_REGISTRY_SERVER_ADDRESS
        value: ":10000"
      - key: MCP_REGISTRY_ENABLE_ANONYMOUS_AUTH
        value: "false"
      - key: MCP_REGISTRY_JWT_PRIVATE_KEY
        value: 120076954d81983a8410babca9dd959d4b29b7569236f184e424744727df5f08

databases:
  - name: mcp-registry-db
    plan: free
    databaseName: mcpregistry
    user: mcpregistry
